Repository CelsiusNetwork/celsius-app, pull requests merged in 2020-03, with the labels that each got.

#595 CN-4783 Adding Appsflyer CUID to events
  app/utils/app-util.js
  app/utils/appsflyer-util.js
  app/utils/mixpanel-analytics/general-analytics.js
Labels: hotfix

#598 CN-4872 Updating CoinPicker to handle Fiat ocins
  app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js
  app/components/screens/SelectCoin/SelectCoin.js
Labels: hotfix

#600 CN-4800 get coins transaction details
  app/components/atoms/TransactionRow/TransactionRow.js
  app/components/molecules/SimplexPaymentsHistory/SimplexPaymentsHistory.js
  app/components/screens/GetCoinsTransactionDetails/GetCoinsTransactionDetails.js
  app/components/screens/GetCoinsTransactionDetails/GetCoinsTransactionDetails.styles.js
  app/components/screens/TransactionDetails/TransactionDetails.js
  app/components/screens/TransactionDetails/TransactionDetailsSections.js
  app/constants/Svgs/TransactionTypeSvgs.js
  app/navigator/flows/walletFlow.js
  app/utils/formatter.js
Labels: hotfix

#604 CN-4872: fiat amount validation
  app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js
Labels: hotfix

#605 CN-4946 added password-meter library and basic strength meter logic
  app/components/atoms/CelInput/CelInputPassword.js
  app/utils/password-util.js
  package.json
Labels: enhancement

#608 CN-4967 changed litecoin foundation logo, fixed styles
  app/components/screens/Home/Home.js
  app/components/screens/Home/Home.styles.js
  app/constants/ASSETS.js
  app/constants/UI.js
  assets/images/PartnerLogos/BitGo.png
  assets/images/PartnerLogos/litecoin-foundation.png
  yarn.lock
Labels: deal, hotfix

#609 CN-4974 ToU linked to external site
  app/components/screens/Profile/Profile.js
Labels: deal, hotfix

#610 CN-4970: Captcha fix
  app/components/screens/Login/Login.js
  app/utils/recaptcha-util.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/RNReanimated/REAUtils.h
  ios/Pods/Headers/Public/RNReanimated/REAUtils.h
  ios/Pods/Local Podspecs/CodePush.podspec.json
  ios/Pods/Local Podspecs/Permission-Camera.podspec.json
  ios/Pods/Local Podspecs/Permission-Contacts.podspec.json
  ios/Pods/Local Podspecs/Permission-LocationWhenInUse.podspec.json
  ios/Pods/Local Podspecs/Permission-MediaLibrary.podspec.json
  ios/Pods/Local Podspecs/Permission-Microphone.podspec.json
  ios/Pods/Local Podspecs/Permission-PhotoLibrary.podspec.json
  ios/Pods/Local Podspecs/RNDeviceInfo.podspec.json
  ios/Pods/Local Podspecs/RNGestureHandler.podspec.json
  ios/Pods/Local Podspecs/RNGoogleSignin.podspec.json
  ios/Pods/Local Podspecs/RNImageCropPicker.podspec.json
  ios/Pods/Local Podspecs/RNPermissions.podspec.json
  ios/Pods/Local Podspecs/RNReanimated.podspec.json
  ios/Pods/Local Podspecs/RNSVG.podspec.json
  ios/Pods/Local Podspecs/react-native-appsflyer.podspec.json
  ios/Pods/Local Podspecs/react-native-camera.podspec.json
  ios/Pods/Local Podspecs/react-native-cameraroll.podspec.json
  ios/Pods/Local Podspecs/react-native-contacts.podspec.json
  ios/Pods/Local Podspecs/react-native-fbsdk.podspec.json
  ios/Pods/Local Podspecs/react-native-netinfo.podspec.json
  ios/Pods/Local Podspecs/react-native-slider.podspec.json
  ios/Pods/Local Podspecs/react-native-webview.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: deal, hotfix

#614 CN-4920: pass strength meter wrap up
  app/components/atoms/Atoms.stories.js
  app/components/atoms/CelInput/CelInputPassword.js
  app/components/atoms/CelInput/CelInputText.js
  app/components/atoms/PassMeterTooltip/PassMeterTooltip.js
  app/components/atoms/PassMeterTooltip/PassMeterTooltip.styles.js
  app/components/atoms/PassStrengthMeter/PassStrengthMeter.js
  app/components/atoms/PassStrengthMeter/PassStrengthMeter.stories.js
  app/components/atoms/PassStrengthMeter/PassStrengthMeter.styles.js
  app/components/screens/ChangePassword/ChangePassword.js
  app/components/screens/RegisterInitial/RegisterInitial.js
  app/constants/ACTIONS.js
  app/constants/DATA.js
  app/redux/forms/formsActions.js
  app/redux/forms/formsReducer.js
  app/utils/password-util.js
Labels: enhancement
